project:
  type: book
  output-dir: _book
book:
  title: Lua Filter Test in Quarto
  chapters:
    - index.qmd
    - references.qmd
bibliography: bib.bib
csl: gb-author-date.csl
format:
  html: default
  docx: default
  pdf: default
